import json
from pathlib import Path

_DIR = Path(__file__).parent


def _load(filename: str):
    return json.loads((_DIR / filename).read_text())


SEC_DOCUMENTS_MAPPING = {
    "SCHEDULE 13D": _load("schedule_13d.json"),
    "SCHEDULE 13D/A": _load("schedule_13d.json"),
    "QUALIF": _load("qualif.json"),
    "EFFECT": _load("effect.json"),
    "13F-HR": _load("13fhr.json"),
    "13F-HR/A": _load("13fhr.json"),
    "D": _load("d.json"),
    "D/A": _load("d.json"),
    "144": _load("144.json"),
    "144/A": _load("144.json"),
    "1-A": _load("1_a.json"),
    "1-A POS": _load("1_a_pos.json"),
    "1-K": _load("1_k.json"),
    "1-K/A": _load("1_k_slash_a.json"),
    "1-Z/A": _load("1_z_slash_a.json"),
    "25-NSE": _load("25_nse.json"),
    "25-NSE/A": _load("25_nse_slash_a.json"),
    "ATS-N-C": _load("ats_n_c.json"),
    "ATS-N-W": _load("ats_n_w.json"),
    "C": _load("c.json"),
    "C-AR": _load("c_ar.json"),
    "C-AR-W": _load("c_ar_w.json"),
    "C-AR/A": _load("c_ar_slash_a.json"),
    "C-TR": _load("c_tr.json"),
    "C-TR-W": _load("c_tr_w.json"),
    "C-U": _load("c_u.json"),
    "C-U-W": _load("c_u_w.json"),
    "C-W": _load("c_w.json"),
    "C/A": _load("c_slash_a.json"),
    "C/A-W": _load("c_slash_a_w.json"),
    "CFPORTAL": _load("cfportal.json"),
    "CFPORTAL-W": _load("cfportal_w.json"),
    "CFPORTAL/A": _load("cfportal_slash_a.json"),
    "COVER PAGE": _load("cover_page.json"),
    "DOS": _load("dos.json"),
    "DOS/A": _load("dos_slash_a.json"),
    "EX-103": _load("ex_103.json"),
    "MA": _load("ma.json"),
    "MA-A": _load("ma_a.json"),
    "MA-I": _load("ma_i.json"),
    "MA-I/A": _load("ma_i_slash_a.json"),
    "MA-W": _load("ma_w.json"),
    "MA/A": _load("ma_slash_a.json"),
    "N-CR": _load("n_cr.json"),
    "N-PX": _load("n_px.json"),
    "N-PX/A": _load("n_px_slash_a.json"),
    "SBSE": _load("sbse.json"),
    "SBSE-A": _load("sbse_a.json"),
    "SBSE-A/A": _load("sbse_a_slash_a.json"),
    "SBSE-BD": _load("sbse_bd.json"),
    "SBSE-BD/A": _load("sbse_bd_slash_a.json"),
    "SBSE-C": _load("sbse_c.json"),
    "SBSE-W": _load("sbse_w.json"),
    "SBSE/A": _load("sbse_slash_a.json"),
    "SBSEF": _load("sbsef.json"),
    "SBSEF-W": _load("sbsef_w.json"),
    "SBSEF/A": _load("sbsef_slash_a.json"),
    "SDR/A": _load("sdr_slash_a.json"),
    "SH-ER": _load("sh_er.json"),
    "TA-1": _load("ta_1.json"),
    "TA-1/A": _load("ta_1_slash_a.json"),
    "TA-2": _load("ta_2.json"),
    "TA-2/A": _load("ta_2_slash_a.json"),
    "TA-W": _load("ta_w.json"),
    "X-17A-5": _load("x_17a_5.json"),
    "X-17A-5/A": _load("x_17a_5_slash_a.json"),
}
